#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat_v2"]
compatibility_date = "2025-10-01"

[[routes]]
pattern = "twikoo.blog.pigeonsz.cc"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "twikoo"
database_id = "27aa01f3-c89d-439f-b9b1-b3f251a85e0d"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://02.oss.pigeonsz.cc"

[placement]
mode = "smart"

[dev]
port = 5000
